// begin header
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:numbered:
:toc: macro
:toc-title: pass:[<b>Table of Contents</b>]
:grafana-production: https://grafana.app-sre.devshift.net/
:grafana-stage: https://grafana.stage.devshift.net/

// end header
= Derive OCM Cluster ID from Connector Cluster ID

toc::[]

== Description

The purpose of this SOP is to describe the process of deriving the OCM cluster id using the connector cluster id. This is useful when you need the retrieve the OCM cluster id for troubleshooting any issues/alert.

== Prerequisites

1. Need Connector cluster id using which OCM cluster id will be retrieved
2. https://github.com/bf2fc6cc711aee1a0c2a/cos-tools/releases[Rhoc cli]
3. https://github.com/openshift-online/ocm-cli[ocm cli]
4. retrieve your https://qaprodauth.cloud.redhat.com/openshift/token[ocm-offline-token] using the _kafka_supporting account
- follow the steps on that page to run the ocm login with the provided token

== Derive OCM cluster ID from Connector Cluster ID

The following command prints the OCM cluster id
----
rhoc cc get --id ${cluster-id} --ocm | jq -r '.status.platform.id'
----
where "${cluster-id}" is connector cluster id.

Following is the example for deriving the OCM cluster id for the cluster with connector cluster id `c9nrsjtcqpu8pmmjl5vg`
----
rhoc cc get --id c9nrsjtcqpu8pmmjl5vg --ocm | jq -r '.status.platform.id'
c021fc2d-d6ed-45b4-ba74-ac51ffca4306
----
Here, `c021fc2d-d6ed-45b4-ba74-ac51ffca4306` is the OCM cluster id.

== Validate

N/A

== Troubleshooting

N/A

