// begin header
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:numbered:
:toc: macro
:toc-title: pass:[<b>Table of Contents</b>]

// end header
= Derive OCM External ID from Connector Cluster ID

toc::[]

== Description

The purpose of this SOP is to describe the process of deriving the OCM external id using the connector cluster id. This is useful when you need the retrieve the OCM external id for troubleshooting any issue/alert.

== Prerequisites

1. https://github.com/bf2fc6cc711aee1a0c2a/cos-tools/releases[RHOC cli]
2. https://github.com/openshift-online/ocm-cli[OCM cli]
3. Retrieve your https://console.redhat.com/openshift/token[ocm-offline-token] using your Red Hat account
- Follow the steps on that page to run the ocm login with the provided token

== Derive OCM external ID from Connector Cluster ID

The following command prints the OCM external id
----
rhoc cc get --id ${cluster-id} | jq -r '.status.platform.id'
----
where "${cluster-id}" is connector cluster id.

Following is the example for deriving the OCM external id for the cluster with connector cluster id `c9nrsjtcqpu8pmmjl5vg`
----
rhoc cc get --id c9nrsjtcqpu8pmmjl5vg | jq -r '.status.platform.id'
c021fc2d-d6ed-45b4-ba74-ac51ffca4306
----
Here, `c021fc2d-d6ed-45b4-ba74-ac51ffca4306` is the OCM external id.

== Validate

N/A

== Troubleshooting

N/A

